- name: OWASP Dependency Track check
  # You may pin to the exact commit or the version.
  # uses: Quobis/action-owasp-dependecy-track-check@2d4568e0746b85da804fe390b519631c88edf8fe
  uses: Quobis/action-owasp-dependecy-track-check@v1.3
  with:
    # URL of OWASP Dependency Track REST API
    url: # default is https://dtrack.quobis.com/
    # Key to access OWASP Dependency Track REST API
    key: # default is USEAVALIDKEY
    # Programming language
    language: # default is nodejs
